### ISSUE TITLE
Early Access Lecture Wednesday

### ISSUE THREAD

**Issue by Hypergeometricdistribution** [gerkovink/markup2021#20]
Hi Gerko,

First of all, best of luck with the surgery!
We were wondering if you could share the pre-recorded lecture with us before Wednesday, if possible?
We would like to use the time Wednesday morning to talk together about any issues we might come across.

Thank you advance. We will here from you,
MSBBSS year 2

**Comment by gerkovink** [comment]
Of course! I wouldn’t have it any other way. I’ll record the lecture tonight and make it available online also tonight.
